// src/screens/supervisor/Orders/EditOrder/EditOrderScreen.styles.ts

import { StyleSheet, Platform } from 'react-native';
import { COLORS, SPACING, RADIUS, SHADOWS, TYPOGRAPHY } from '@/theme';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  loadingWrap: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.lg,
    paddingTop: Platform.OS === 'ios' ? 50 : SPACING.lg,
    paddingBottom: SPACING.md,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  backIcon: { fontSize: 22, color: COLORS.textPrimary },
  headerTitle: { ...TYPOGRAPHY.h3, color: COLORS.navy, textAlign: 'center' },
  headerGuia: { ...TYPOGRAPHY.caption, color: COLORS.textSecondary, textAlign: 'center' },
  content: { padding: SPACING.lg, paddingBottom: 100 },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: SPACING.lg,
    marginBottom: SPACING.lg,
    ...SHADOWS.card,
  },
  cardTitle: { ...TYPOGRAPHY.h3, color: COLORS.navy, marginBottom: 4 },
  cardSubtitle: { ...TYPOGRAPHY.caption, color: COLORS.textSecondary, marginBottom: SPACING.lg },
  fieldLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.textMuted,
    letterSpacing: 1,
    marginBottom: SPACING.xs,
    marginTop: SPACING.md,
  },
  trackingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: COLORS.bg,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
  },
  trackingValue: { ...TYPOGRAPHY.bodyMedium, color: COLORS.textPrimary },
  lockIcon: { fontSize: 16, color: COLORS.textMuted },
  input: {
    backgroundColor: COLORS.bg,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.sm,
    fontSize: 15,
    color: COLORS.textPrimary,
  },
  addressText: { ...TYPOGRAPHY.body, color: COLORS.textSecondary },
  btnRow: { flexDirection: 'row', gap: SPACING.md, marginTop: SPACING.xl },
  cancelBtn: {
    flex: 1,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: RADIUS.md,
    paddingVertical: SPACING.md,
    alignItems: 'center',
  },
  cancelBtnText: { ...TYPOGRAPHY.bodyMedium, color: COLORS.textPrimary },
  saveBtn: {
    flex: 2,
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.md,
    paddingVertical: SPACING.md,
    alignItems: 'center',
  },
  saveBtnText: { ...TYPOGRAPHY.button, color: COLORS.white },
  estadoChip: {
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.xs,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.bg,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginRight: SPACING.sm,
  },
  estadoChipActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  estadoChipText: { fontSize: 13, color: COLORS.textSecondary, fontWeight: '600' },
  estadoChipTextActive: { color: COLORS.white },
  repartidorCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.md,
    padding: SPACING.md,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: SPACING.sm,
  },
  repartidorCardActive: { borderColor: COLORS.primary, backgroundColor: '#FFF7F0' },
  repartidorAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.navy,
    alignItems: 'center',
    justifyContent: 'center',
  },
  repartidorNombre: { ...TYPOGRAPHY.bodyMedium, color: COLORS.textPrimary },
  repartidorSub: { ...TYPOGRAPHY.caption, color: COLORS.textSecondary },
});