// src/screens/supervisor/Orders/OrdersScreen.styles.ts

import { StyleSheet, Platform } from 'react-native';
import { COLORS, SPACING, RADIUS, SHADOWS, TYPOGRAPHY } from '@/theme';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: SPACING.lg,
    paddingTop: Platform.OS === 'ios' ? 50 : SPACING.lg,
    paddingBottom: SPACING.md,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  headerTitle: { ...TYPOGRAPHY.h2, color: COLORS.navy },
  headerSubtitle: { ...TYPOGRAPHY.caption, color: COLORS.textSecondary, marginTop: 2 },
  newBtn: {
    backgroundColor: COLORS.primary,
    borderRadius: RADIUS.full,
    paddingHorizontal: SPACING.lg,
    paddingVertical: SPACING.sm,
  },
  newBtnText: { color: COLORS.white, fontWeight: '700', fontSize: 13 },
  searchRow: {
  flexDirection:     'row',
  alignItems:        'center',
  gap:               SPACING.sm,
  paddingHorizontal: SPACING.lg,
  paddingTop:        SPACING.md,
  paddingBottom:     0,
  backgroundColor:   COLORS.white,
},
  searchWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.bg,
    borderRadius: RADIUS.md,
    paddingHorizontal: SPACING.md,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  searchIcon: { fontSize: 16, marginRight: SPACING.sm },
  searchInput: { flex: 1, paddingVertical: SPACING.sm, color: COLORS.textPrimary },
  filterBtn: {
    width: 40,
    height: 40,
    backgroundColor: COLORS.bg,
    borderRadius: RADIUS.md,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
filtrosScroll: { backgroundColor: COLORS.white, marginTop: -1 },
filtrosContent: {
  paddingHorizontal: SPACING.lg,
  paddingVertical:   SPACING.sm,
  gap:               SPACING.sm,
  alignItems:        'center',
},
filtroChip: {
  paddingHorizontal: SPACING.lg,
  paddingVertical:   6,
  borderRadius:      RADIUS.full,
  backgroundColor:   COLORS.bg,
  borderWidth:       1,
  borderColor:       COLORS.border,
  height:            34,
  justifyContent:    'center' as const,
},
  filtroChipActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  filtroText: { fontSize: 13, color: COLORS.textSecondary, fontWeight: '600' },
  filtroTextActive: { color: COLORS.white },
  lista: { padding: SPACING.lg },
  emptyWrap: { alignItems: 'center', paddingVertical: 40 },
  emptyText: { ...TYPOGRAPHY.body, color: COLORS.textSecondary },
  orderCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: SPACING.lg,
    marginBottom: SPACING.md,
    ...SHADOWS.card,
  },
  orderTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: SPACING.sm },
  guiaLabel: { fontSize: 10, fontWeight: '700', color: COLORS.textMuted, letterSpacing: 1 },
  guiaNum: { ...TYPOGRAPHY.h3, color: COLORS.navy },
  estadoBadge: { borderRadius: RADIUS.full, paddingHorizontal: SPACING.md, paddingVertical: 4 },
  estadoText: { fontSize: 11, fontWeight: '700' },
  clienteRow: { flexDirection: 'row', alignItems: 'center', gap: SPACING.sm, marginBottom: 2 },
  clienteIcon: { fontSize: 14 },
  clienteNombre: { ...TYPOGRAPHY.bodyMedium, color: COLORS.textPrimary },
  direccionText: { ...TYPOGRAPHY.caption, color: COLORS.textSecondary, marginBottom: SPACING.md },
  repartidorRow: { flexDirection: 'row', alignItems: 'center', gap: SPACING.sm, marginBottom: SPACING.md },
  repartidorAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.navy,
    alignItems: 'center',
    justifyContent: 'center',
  },
  repartidorNombre: { ...TYPOGRAPHY.bodyMedium, color: COLORS.textSecondary },
  accionesRow: { flexDirection: 'row', justifyContent: 'flex-end', gap: SPACING.sm },
  editBtn: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  editBtnText: { fontSize: 13, color: COLORS.textPrimary, fontWeight: '600' },
  moreBtn: {
    paddingHorizontal: SPACING.md,
    paddingVertical: SPACING.xs,
    borderRadius: RADIUS.sm,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  moreBtnText: { fontSize: 13, color: COLORS.textPrimary },
});