// src/screens/repartidor/MiRuta/MiRutaScreen.styles.ts

import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F1F5F9' },
  navBar: {
    height: 72,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  navTitle: { fontSize: 20, fontWeight: '700', color: '#0F172A' },
  avatarMini: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#FF7D29',
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollContent: { padding: 18, paddingBottom: 120 },
  bodegaCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 18,
    marginBottom: 24,
    elevation: 2,
  },
  bodegaHeader: { flexDirection: 'row', alignItems: 'center', gap: 14, marginBottom: 18 },
  iconContainer: {
    width: 52,
    height: 52,
    borderRadius: 14,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  puntoLabel: { fontSize: 11, fontWeight: '700', color: '#737373', marginBottom: 3 },
  bodegaNombre: { fontSize: 16, fontWeight: '700', color: '#111827', marginBottom: 2 },
  bodegaCiudad: { fontSize: 13, color: '#737373' },
  wazeBtn: {
    height: 56,
    backgroundColor: '#FF7D29',
    borderRadius: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 10,
  },
  wazeBtnText: { color: '#FFFFFF', fontSize: 16, fontWeight: '600' },
  filterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 18,
  },
  sectionTitle: { fontSize: 17, fontWeight: '600', color: '#111827' },
  filterIcons: { flexDirection: 'row' },
  deliveryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 22,
    marginBottom: 22,
    elevation: 2,
  },
  activeCard: { borderLeftWidth: 3, borderLeftColor: '#FF7D29' },
  cardHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' },
  locationInfo: { flexDirection: 'row', alignItems: 'center', flex: 1 },
  direccionText: { fontSize: 16, fontWeight: '700', color: '#0F172A', flex: 1 },
  proximoBadge: { backgroundColor: '#FFF1E7', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 999 },
  proximoText: { color: '#B45309', fontSize: 10, fontWeight: '700' },
  ciudadSub: { marginTop: 8, marginBottom: 20, marginLeft: 26, color: '#64748B', fontSize: 13, fontWeight: '500' },
  clientInfoGrid: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20 },
  infoBlock: { flex: 1 },
  fieldLabel: { fontSize: 11, fontWeight: '700', color: '#A1A1AA', marginBottom: 6 },
  fieldValue: { fontSize: 15, fontWeight: '600', color: '#111827', lineHeight: 24 },
  phoneLink: { color: '#C26A2D', textDecorationLine: 'underline' },
  observacionesBox: { backgroundColor: '#F1F5F9', borderRadius: 12, padding: 14, marginBottom: 24 },
  obsText: { color: '#334155', lineHeight: 24, fontSize: 14 },
  actionBtnActive: {
    backgroundColor: '#0F2B46',
    height: 54,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  actionBtnTextActive: { color: '#FFFFFF', fontWeight: '600', fontSize: 16 },
  actionBtnOutline: {
    borderWidth: 1.5,
    borderColor: '#0F2B46',
    height: 54,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  actionBtnTextOutline: { color: '#0F2B46', fontWeight: '600', fontSize: 16 },
});