// src/screens/repartidor/Pedidos/PedidosScreen.styles.ts

import { StyleSheet } from 'react-native';
import { COLORS, SPACING, RADIUS, SHADOWS } from '@/theme';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.bg },
  scrollContent: { padding: SPACING.lg, paddingBottom: 100 },
  earningsCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    ...SHADOWS.card,
  },
  earningsInfo: {},
  earningsLabel: { fontSize: 14, color: COLORS.textSecondary },
  earningsValue: { fontSize: 24, color: COLORS.navy, fontWeight: '700' },
  iconWallet: {
    width: 50,
    height: 50,
    borderRadius: RADIUS.md,
    backgroundColor: '#FFF0E8',
    justifyContent: 'center',
    alignItems: 'center',
  },
  statsRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 15 },
  statBox: { flex: 1, backgroundColor: COLORS.white, borderRadius: RADIUS.lg, padding: 15, ...SHADOWS.card },
  statBoxSpacing: { marginRight: 15 },
  statIcon: { fontSize: 20 },
  statNum: { fontSize: 18, marginVertical: 5, fontWeight: '700' },
  statLabel: { fontSize: 12, color: COLORS.textSecondary },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.md,
    paddingHorizontal: 15,
    marginTop: 20,
    ...SHADOWS.card,
  },
  searchIcon: { fontSize: 16 },
  searchInput: { flex: 1, paddingVertical: 12, marginLeft: 10 },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 25,
    marginBottom: 15,
  },
  sectionTitle: { fontSize: 18, color: COLORS.navy, fontWeight: '700' },
  sectionCount: { fontSize: 13, color: COLORS.textSecondary },
  orderCard: {
    backgroundColor: COLORS.white,
    borderRadius: RADIUS.lg,
    padding: 20,
    marginBottom: 15,
    ...SHADOWS.card,
  },
  orderHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  orderId: { fontSize: 12, color: COLORS.textMuted, fontWeight: '700' },
  statusBadge: { borderRadius: 5, paddingHorizontal: 8, paddingVertical: 4 },
  statusOrange: { backgroundColor: '#FFF0E8' },
  statusBlue: { backgroundColor: '#E0E7FF' },
  statusText: { fontSize: 10, color: COLORS.primary, fontWeight: '700' },
  clientName: { fontSize: 16, color: COLORS.navy, fontWeight: '700' },
  locRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8 },
  locText: { flex: 1, fontSize: 13, color: COLORS.textSecondary },
  orderFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  footerLabel: { fontSize: 12, color: COLORS.textSecondary },
  footerVal: { fontSize: 16, color: COLORS.navy, fontWeight: '700' },
  actionBtn: { backgroundColor: COLORS.navy, borderRadius: RADIUS.md, paddingVertical: 10, paddingHorizontal: 20 },
  actionBtnText: { fontSize: 13, color: COLORS.white, fontWeight: '700' },
  fabAdd: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    ...SHADOWS.card,
  },
  fabText: { fontSize: 30, color: COLORS.white },
});