// src/screens/admin/Roles/RolesScreen.styles.ts

import { StyleSheet, Platform } from 'react-native';
import { COLORS, SPACING, RADIUS, SHADOWS, TYPOGRAPHY } from '@/theme';

export default StyleSheet.create({
  container:    { flex: 1, backgroundColor: COLORS.bg },
  header: {
    flexDirection:     'row',
    justifyContent:    'space-between',
    alignItems:        'center',
    paddingHorizontal: SPACING.lg,
    paddingTop:        Platform.OS === 'ios' ? 50 : SPACING.lg,
    paddingBottom:     SPACING.md,
    backgroundColor:   COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  headerTitle:   { ...TYPOGRAPHY.h2, color: COLORS.navy },
  content:       { padding: SPACING.lg, paddingBottom: 100 },
  pageTitle:     { ...TYPOGRAPHY.h1, color: COLORS.navy, marginBottom: 4 },
  pageSubtitle:  { ...TYPOGRAPHY.caption, color: COLORS.textSecondary, marginBottom: SPACING.xl },
  kpiCard: {
    backgroundColor: COLORS.white,
    borderRadius:    RADIUS.lg,
    padding:         SPACING.lg,
    marginBottom:    SPACING.md,
    ...SHADOWS.card,
  },
  kpiTop: {
    flexDirection:  'row',
    justifyContent: 'space-between',
    alignItems:     'center',
    marginBottom:   SPACING.sm,
  },
  kpiBadge: {
    borderRadius:      RADIUS.full,
    paddingHorizontal: SPACING.sm,
    paddingVertical:   3,
  },
  kpiBadgeText:  { fontSize: 11, fontWeight: '700' },
  kpiLabel:      { ...TYPOGRAPHY.caption, color: COLORS.textSecondary, marginBottom: 2 },
  kpiValue:      { fontSize: 22, fontWeight: '800', color: COLORS.navy },
  kpiSub:        { fontSize: 12, color: COLORS.textMuted, marginTop: 2 },
  searchWrap: {
    flexDirection:     'row',
    alignItems:        'center',
    backgroundColor:   COLORS.white,
    borderRadius:      RADIUS.md,
    borderWidth:       1,
    borderColor:       COLORS.border,
    paddingHorizontal: SPACING.md,
    marginBottom:      SPACING.md,
    ...SHADOWS.card,
  },
  searchInput:   { flex: 1, paddingVertical: SPACING.md, fontSize: 14, color: COLORS.textPrimary },
  tableCard: {
    backgroundColor: COLORS.white,
    borderRadius:    RADIUS.lg,
    padding:         SPACING.lg,
    ...SHADOWS.card,
  },
  tableHeader: {
    flexDirection:     'row',
    paddingBottom:     SPACING.sm,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    marginBottom:      SPACING.sm,
  },
  tableHeaderText: { fontSize: 11, fontWeight: '700', color: COLORS.textMuted },
  tableRow: {
    flexDirection:     'row',
    paddingVertical:   SPACING.md,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    alignItems:        'center',
  },
  avatarSmall: {
    width:        32,
    height:       32,
    borderRadius: 16,
    alignItems:   'center',
    justifyContent: 'center',
    marginRight:  SPACING.sm,
  },
  avatarText:    { color: COLORS.white, fontWeight: '700', fontSize: 13 },
  clienteNombre: { fontSize: 13, fontWeight: '600', color: COLORS.textPrimary },
  clienteNit:    { fontSize: 11, color: COLORS.textMuted },
  pagination: {
    flexDirection:  'row',
    justifyContent: 'space-between',
    alignItems:     'center',
    marginTop:      SPACING.md,
  },
  paginationText: { fontSize: 12, color: COLORS.textSecondary },
  paginationBtn: {
    width:          32,
    height:         32,
    borderRadius:   16,
    borderWidth:    1,
    borderColor:    COLORS.border,
    alignItems:     'center',
    justifyContent: 'center',
  },
});