// src/screens/repartidor/ConfirmarEntrega/ConfirmarEntregaScreen.styles.ts

import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F1F5F9',
  },
  header: {
    height: 65,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0F172A',
  },
  headerSpace: { width: 24 },
  scrollContent: { padding: 16, paddingBottom: 60 },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    elevation: 2,
  },
  badge: {
    alignSelf: 'flex-start',
    backgroundColor: '#EFF6FF',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginBottom: 14,
  },
  badgeText: { color: '#2563EB', fontSize: 11, fontWeight: '700' },
  locationRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  title: { fontSize: 28, fontWeight: '700', color: '#111827', marginBottom: 18 },
  divider: { height: 1, backgroundColor: '#E5E7EB', marginBottom: 18 },
  label: { fontSize: 11, fontWeight: '700', color: '#94A3B8', marginBottom: 6, marginTop: 12 },
  value: { fontSize: 16, color: '#111827', lineHeight: 24 },
  sectionTitle: { fontSize: 18, fontWeight: '700', color: '#111827', marginBottom: 10 },
  sectionDescription: { color: '#64748B', lineHeight: 22, marginBottom: 18 },
  photoBox: {
    height: 180,
    borderWidth: 2,
    borderColor: '#CBD5E1',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
  },
  photoText: { marginTop: 10, fontWeight: '600', color: '#475569' },
  input: {
    height: 54,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 12,
    paddingHorizontal: 16,
    backgroundColor: '#FFFFFF',
    marginBottom: 14,
  },
  textArea: {
    minHeight: 110,
    borderWidth: 1,
    borderColor: '#CBD5E1',
    borderRadius: 12,
    padding: 16,
    textAlignVertical: 'top',
    backgroundColor: '#FFFFFF',
  },
  optionActive: {
    height: 54,
    borderRadius: 14,
    backgroundColor: '#F8FAFC',
    borderWidth: 1.5,
    borderColor: '#0F172A',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  option: {
    height: 54,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    justifyContent: 'center',
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  optionText: { marginLeft: 10, fontSize: 15, fontWeight: '600', color: '#111827' },
  confirmBtn: {
    height: 58,
    backgroundColor: '#FF7D29',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
  },
  confirmBtnText: { color: '#FFFFFF', fontSize: 17, fontWeight: '700' },
});